### ISSUE TITLE
FATA[0354] deploying quotes: exit status 1 : Unable to mount volumes

### ISSUE THREAD

**Issue by sandeep-mishra** [balchua/demo#1]
I am trying to deploy quotes using following ReadMe.
`skaffold run -p local`
results in following error:
`
Error: release: "quotes" not found
Helm release quotes not installed. Installing...
No requirements found in quote-charts/charts.
Error: timed out waiting for the condition
WARN[0354] error retrieving helm deployment info: Error: release: "quotes" not found 
Deploy complete in 5m10.606861983s
FATA[0354] deploying quotes: exit status 1 `

I can see a an to createContainer in microk8s cluster which fails after 5 mins.
The pod following error:
`  Warning  FailedMount  118s                 kubelet, sandeep-hp-pavilion-14-notebook-pc  Unable to mount volumes for pod "quotes-db-schema-migrate-h8tl4_my-project(da964084-09e7-436a-bfba-e629a4b14bf9)": timeout expired waiting for volumes to attach or mount for pod "my-project"/"quotes-db-schema-migrate-h8tl4". list of unmounted volumes=[sql-config]. list of unattached volumes=[sql-config default-token-wc4bk]`

I have already checked that mount directory exists and has full permission 777.
local docker registery is running on 5000.

**Comment by balchua** [comment]
If you dont have a persistence volume configured, you can change the `values-local.yaml` and set the persistence.enabled to false.

```
db:
  pvc:
    enabled: false
```
This will use `emptyDir`.  When the pod restarts, the data goes away with it.

**Comment by balchua** [comment]
Since the setup is complete, closing this issue.
